@echo off
echo Installing dependencies...
npm install prisma @prisma/client --no-fund --no-audit
echo Running Prisma generate...
npx prisma generate
echo Pushing schema to database...
npx prisma db push
echo Starting Next.js development server...
npm run dev
